# Safety Parameters Configuration
# FRANKA ROS2 Step 4: 安全制御システム設定
# Step 1品質継承: 設定外部化、Mock禁止、Step 2衝突監視基盤活用

# 安全制限値 (FRANKA Panda仕様ベース)
safety_limits:
  # 関節制限
  max_joint_velocity: [2.6, 2.6, 2.6, 2.6, 3.1, 3.1, 3.1]  # 関節最大速度 (rad/s)
  max_joint_acceleration: [15.0, 15.0, 15.0, 15.0, 20.0, 20.0, 20.0]  # 関節最大加速度 (rad/s²)
  max_joint_jerk: [7500.0, 7500.0, 7500.0, 7500.0, 10000.0, 10000.0, 10000.0]  # 関節最大ジャーク (rad/s³)
  
  # カルテシアン制限
  max_cartesian_velocity: 1.7        # カルテシアン最大速度 (m/s)
  max_cartesian_acceleration: 13.0   # カルテシアン最大加速度 (m/s²)
  max_cartesian_jerk: 6500.0         # カルテシアン最大ジャーク (m/s³)
  
  # 力・トルク制限
  max_force: 87.0                    # 最大力 (N)
  max_torque: [87.0, 87.0, 87.0, 87.0, 12.0, 12.0, 12.0]  # 最大トルク (Nm)
  
  # ワークスペース制限
  workspace_limits:
    x: [-0.855, 0.855]               # X軸制限 (m)
    y: [-0.855, 0.855]               # Y軸制限 (m)
    z: [0.0, 1.19]                   # Z軸制限 (m)
    roll: [-3.14159, 3.14159]        # ロール制限 (rad)
    pitch: [-3.14159, 3.14159]       # ピッチ制限 (rad)
    yaw: [-3.14159, 3.14159]         # ヨー制限 (rad)
  
  # 衝突・接触制限
  collision_threshold: 0.05          # 衝突検出閾値 (m)
  contact_force_threshold: 20.0      # 接触力閾値 (N)
  emergency_stop_deceleration: 5.0   # 緊急停止減速度 (m/s²)

# 監視パラメータ
monitoring_parameters:
  monitoring_frequency: 50.0         # 監視周波数 (Hz)
  violation_history_size: 100        # 違反履歴サイズ
  emergency_stop_timeout: 2.0        # 緊急停止タイムアウト (秒)
  recovery_timeout: 10.0             # 回復タイムアウト (秒)
  force_averaging_window: 10         # 力平均化ウィンドウ (サンプル数)
  state_update_rate: 20.0            # 状態更新レート (Hz)
  metrics_update_rate: 10.0          # メトリクス更新レート (Hz)

# 安全レベル設定
safety_levels:
  normal_operation:
    velocity_scaling: 1.0            # 速度スケーリング
    force_scaling: 1.0               # 力スケーリング
    monitoring_sensitivity: 1.0      # 監視感度
    
  warning_level:
    velocity_scaling: 0.8            # 速度80%制限
    force_scaling: 0.8               # 力80%制限
    monitoring_sensitivity: 1.2      # 監視感度120%
    
  critical_level:
    velocity_scaling: 0.5            # 速度50%制限
    force_scaling: 0.6               # 力60%制限
    monitoring_sensitivity: 1.5      # 監視感度150%
    
  emergency_level:
    velocity_scaling: 0.0            # 完全停止
    force_scaling: 0.0               # 力無効化
    monitoring_sensitivity: 2.0      # 最大監視感度

# 違反タイプ別設定
violation_type_settings:
  collision_risk:
    severity_threshold: [0.03, 0.05, 0.08, 0.12, 0.15]  # 重要度閾値 (m)
    response_action: ["warning", "slow_down", "stop", "emergency_stop", "system_halt"]
    escalation_time: [2.0, 1.0, 0.5, 0.2, 0.0]  # エスカレーション時間 (秒)
    
  excessive_force:
    severity_threshold: [60.0, 80.0, 100.0, 120.0, 140.0]  # 重要度閾値 (N)
    response_action: ["warning", "force_limit", "slow_down", "stop", "emergency_stop"]
    escalation_time: [1.0, 0.5, 0.3, 0.1, 0.0]
    
  joint_limit:
    severity_threshold: [0.8, 0.9, 0.95, 0.98, 1.0]  # 制限値に対する比率
    response_action: ["warning", "trajectory_modify", "slow_down", "stop", "emergency_stop"]
    escalation_time: [2.0, 1.0, 0.5, 0.2, 0.0]
    
  cartesian_limit:
    severity_threshold: [0.85, 0.92, 0.96, 0.99, 1.0]  # ワークスペース制限に対する比率
    response_action: ["warning", "trajectory_modify", "return_safe", "stop", "emergency_stop"]
    escalation_time: [3.0, 2.0, 1.0, 0.5, 0.0]
    
  velocity_limit:
    severity_threshold: [0.8, 0.9, 0.95, 0.98, 1.0]  # 速度制限に対する比率
    response_action: ["warning", "velocity_limit", "slow_down", "stop", "emergency_stop"]
    escalation_time: [1.0, 0.5, 0.3, 0.1, 0.0]
    
  communication_failure:
    severity_threshold: [1.0, 2.0, 3.0, 5.0, 10.0]  # 通信断絶時間 (秒)
    response_action: ["warning", "retry", "safe_mode", "stop", "emergency_stop"]
    escalation_time: [5.0, 3.0, 2.0, 1.0, 0.0]

# 緊急停止設定
emergency_stop_settings:
  activation_conditions:
    force_exceeded: true             # 力超過
    collision_detected: true         # 衝突検出
    workspace_violation: true        # ワークスペース違反
    communication_loss: true         # 通信断絶
    system_error: true              # システムエラー
    manual_trigger: true            # 手動トリガー
    
  stop_behavior:
    deceleration_profile: "smooth"   # 減速プロファイル ("smooth", "fast", "immediate")
    brake_engagement: true           # ブレーキ作動
    power_cutoff: false             # 電源遮断 (false = 位置保持)
    status_notification: true       # 状態通知
    
  recovery_requirements:
    manual_reset_required: true      # 手動リセット必要
    system_check_required: true      # システムチェック必要
    safety_clearance_required: true  # 安全クリアランス必要
    supervisor_approval: false       # 監督者承認 (開発環境では false)

# Step 2基盤活用: 衝突監視統合設定
collision_monitoring_integration:
  enable_step2_collision_monitor: true    # Step 2衝突監視有効化
  collision_prediction_enabled: true      # 衝突予測有効
  trajectory_safety_check: true           # 軌道安全性確認
  real_time_collision_avoidance: true     # リアルタイム衝突回避
  
  # 衝突監視パラメータ
  collision_parameters:
    prediction_horizon: 2.0              # 予測時間 (秒)
    safety_margin: 0.02                  # 安全マージン (2cm)
    collision_detection_sensitivity: 0.8  # 検出感度
    false_positive_threshold: 0.05       # 誤検出閾値

# 安全監査・ログ設定
safety_audit_logging:
  comprehensive_logging: true        # 包括的ログ記録
  violation_detailed_log: true       # 違反詳細ログ
  safety_metrics_log: true          # 安全メトリクスログ
  audit_trail_enabled: true         # 監査証跡有効
  
  # ログ保持設定
  log_retention:
    safety_events: 90                # 安全イベントログ保持 (日)
    violation_records: 60            # 違反記録保持 (日)
    performance_metrics: 30          # 性能メトリクス保持 (日)
    audit_trail: 365                # 監査証跡保持 (日)
    
  # ログレベル設定
  log_levels:
    safety_violations: "ERROR"       # 安全違反ログレベル
    warning_events: "WARN"           # 警告イベントログレベル
    normal_operations: "INFO"        # 通常動作ログレベル
    debug_information: "DEBUG"       # デバッグ情報ログレベル

# 安全認証・準拠設定
safety_compliance:
  iso_13849_compliance: true         # ISO 13849準拠
  iec_61508_compliance: true         # IEC 61508準拠
  risk_assessment_level: "PLd"       # パフォーマンスレベルd
  safety_integrity_level: "SIL2"     # 安全完整性レベル2
  
  # 準拠要件
  compliance_requirements:
    safety_function_testing: true    # 安全機能テスト
    periodic_validation: true        # 定期検証
    failure_mode_analysis: true      # 故障モード解析
    documentation_complete: true     # 文書化完了

# 性能監視・最適化設定
performance_safety_optimization:
  adaptive_safety_limits: false      # 適応的安全制限 (保守的にfalse)
  predictive_safety: true           # 予測安全
  machine_learning_safety: false    # 機械学習安全 (未実装)
  continuous_improvement: true       # 継続的改善
  
  # 最適化パラメータ
  optimization_parameters:
    safety_performance_tradeoff: 0.8 # 安全-性能トレードオフ (80%安全重視)
    false_alarm_tolerance: 0.05      # 誤警報許容率 (5%)
    response_time_target: 0.1        # 応答時間目標 (100ms)
    availability_target: 0.99        # 可用性目標 (99%)

# テスト・検証設定
safety_testing_verification:
  automated_safety_testing: true     # 自動安全テスト
  safety_simulation: true           # 安全シミュレーション
  boundary_condition_testing: true  # 境界条件テスト
  fault_injection_testing: true     # 故障注入テスト
  
  # テストパラメータ
  testing_parameters:
    test_frequency: "weekly"         # テスト頻度
    test_coverage_target: 0.95       # テストカバレッジ目標 (95%)
    test_automation_level: 0.8       # テスト自動化レベル (80%)
    verification_methods: ["simulation", "formal_verification", "testing"]

# 品質保証設定
quality_assurance:
  step1_inheritance_verification: true    # Step 1継承確認
  step2_integration_verification: true    # Step 2統合確認
  mock_detection_enabled: true           # Mock検出有効
  configuration_validation: true         # 設定検証
  safety_standards_compliance: true      # 安全基準準拠
  
  # 品質メトリクス
  quality_metrics:
    safety_availability: 0.9999       # 安全可用性目標 (99.99%)
    mean_time_to_failure: 8760        # 平均故障時間 (時間) = 1年
    mean_time_to_repair: 1            # 平均修復時間 (時間)
    false_positive_rate: 0.01         # 誤検知率 (1%)
    false_negative_rate: 0.001        # 見逃し率 (0.1%)